[package]
name = "back-end"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
axum = "0.7.4"
serde_json = "1.0.113"
serde = "1.0.196"
tower-http = { version = "0.5.1", features = ["full"] }
tower = "0.4"
lazy_static = "1.4"
futures = "0.3.30"